### PR TITLE
Closing #18, Fixing #15 and adding composer support

### PR DESCRIPTION
**Pull request by cliffparnitzky**
- Added support for dates in the past including today (#18)
- Fixes problem when selecting option for all dates (#15)
- Added composer support

### CODE REVIEW

**Comment by aschempp** [comment]
Great! Could you add a script to migrate existing values? Also, please call the file `update.php` and include it in composer.json, we'll then add `runonce.php` to ER.

**Comment by cliffparnitzky** [comment]
Any chance to get an example what exacly to do?

**Comment by cliffparnitzky** [comment]
@aschempp Okay, i added a runonce and included it in composer.json ... is that right?

**Comment by aschempp** [comment]
Looks good! However, you should not name the file `runonce.php`, because it will be deleted by Contao and Composer does not like that. Please name it `update.php`, we will then add a `runonce.php` to ER which will simply include the `update.php`.

**Comment by cliffparnitzky** [comment]
Ah, yeah. Thanks. Now i understood. Moved and renamed the file in last commit.

**Pull request merged**
